version: 2
jobs:
  build:
    working_directory: ~/repo
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install Python 3.8
          command: |
            sudo apt-get update
            sudo apt-get install build-essential
            sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev \
                libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
            cd /opt
            sudo wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
            sudo tar xzf Python-3.8.0.tgz

      - run:
          name: Set up pipenv and install requirements
          command: |
            sudo python -m pip install pipenv
            pipenv install

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ./venv

      - run:
          name: Compile files
          command: |
            pipenv run python -m compileall main.py modules utils -fq

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-reports
          destination: test-reports
