version: 2
jobs:
  build:
    working_directory: ~/repo
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install Python 3.8
          command: |
            sudo apt-get install python3.8

      - run:
          name: Set up pipenv and install requirements
          command: |
            sudo python3.8 -m pip install pipenv
            pipenv install

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ./venv

      - run:
          name: Compile files
          command: |
            pipenv run python3.8 -m compileall main.py modules utils -fq

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-reports
          destination: test-reports
