version: 2
jobs:
  build:
    working_directory: ~/repo
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout

      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          command: |
            sudo pip install pipenv
            pipenv install

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ./venv

      - run:
          command: |
            pipenv run python main.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
