---
version: 0.0.0
owners:
  - 173237945149423619 # Please keep my ID here

colors:
  main: 11533055
  error: 15158332

prefixes:
  main:
    - n!
  debug:
    - n!!

time_format: "%A, %B %d %Y @ %I:%M%p %Z"